export const ASSIGNMENT_FORMATS: { value: string; label: string }[] = [
  { value: "report", label: "보고서" },
  { value: "thesis", label: "논문" },
  { value: "presentation", label: "발표자료" },
  { value: "essay", label: "에세이" },
  { value: "research_proposal", label: "연구 계획서" },
  { value: "literature_review", label: "문헌 연구" },
  { value: "case_study", label: "사례 연구" },
  { value: "code_documentation", label: "코드 설명서" },
  { value: "technical_report", label: "기술 보고서" },
  { value: "book_report", label: "독후감" },
]

export const WRITING_STYLES: { value: string; label: string }[] = [
  { value: "formal", label: "격식체" },
  { value: "informal", label: "비격식체 (일상적)" },
  { value: "academic", label: "학술적" },
  { value: "descriptive", label: "설명적" },
  { value: "persuasive", label: "설득적" },
  { value: "narrative", label: "서사적" },
]

export const TOC_OPTIONS_BY_FORMAT: Record<string, string[]> = {
  report: [
    "표지",
    "목차",
    "요약",
    "서론",
    "이론적 배경",
    "본론 1",
    "본론 2",
    "본론 3",
    "실험/연구 방법",
    "결과",
    "논의",
    "결론",
    "제언",
    "참고문헌",
    "부록",
  ],
  thesis: [
    "표지",
    "제출서",
    "인준서",
    "감사의 글",
    "국문초록",
    "영문초록",
    "목차",
    "표목차",
    "그림목차",
    "I. 서론",
    "  1.1 연구의 필요성 및 목적",
    "  1.2 연구 문제",
    "  1.3 연구 범위 및 제한점",
    "  1.4 용어 정의",
    "II. 이론적 배경",
    "  2.1 선행 연구 고찰",
    "  2.2 관련 이론",
    "III. 연구 방법",
    "  3.1 연구 설계",
    "  3.2 연구 대상",
    "  3.3 측정도구",
    "  3.4 자료수집 절차",
    "  3.5 자료분석 방법",
    "IV. 연구 결과",
    "  4.1 기술통계 분석",
    "  4.2 가설 검증 결과",
    "V. 논의",
    "  5.1 연구 결과 요약",
    "  5.2 연구 결과 해석",
    "  5.3 시사점",
    "VI. 결론 및 제언",
    "  6.1 결론",
    "  6.2 제언",
    "  6.3 후속 연구를 위한 제언",
    "참고문헌",
    "부록",
    "Abstract",
  ],
  presentation: [
    "표지 슬라이드",
    "목차 슬라이드",
    "도입/문제 제기",
    "핵심 내용 1",
    "핵심 내용 2",
    "핵심 내용 3",
    "사례/데이터 분석",
    "결론/요약",
    "향후 계획/제언",
    "Q&A",
    "감사 슬라이드",
  ],
  essay: ["서론 (도입)", "본론 1 (주장/근거)", "본론 2 (주장/근거)", "본론 3 (반론 및 재반론)", "결론 (요약 및 제언)"],
  research_proposal: [
    "연구 제목",
    "연구 배경 및 필요성",
    "연구 목적 및 내용",
    "연구 방법 및 절차",
    "예상 결과 및 기대 효과",
    "연구 일정",
    "참고문헌",
    "연구비 예산 (필요시)",
  ],
  literature_review: ["서론", "주제별 문헌 고찰 1", "주제별 문헌 고찰 2", "종합 및 비판", "결론", "참고문헌"],
  case_study: ["사례 개요", "문제점 분석", "이론적 접근", "해결 방안 제시", "결과 및 평가", "결론 및 시사점"],
  code_documentation: [
    "개요 (Overview)",
    "설치 방법 (Installation)",
    "사용 방법 (Usage)",
    "API 레퍼런스",
    "예제 코드",
    "기여 방법 (Contributing)",
    "라이선스",
  ],
  technical_report: [
    "표지",
    "초록",
    "목차",
    "용어 정의",
    "서론",
    "기술적 배경",
    "설계 및 구현",
    "실험 및 결과",
    "분석 및 토의",
    "결론",
    "참고문헌",
    "부록",
  ],
  book_report: [
    "책 정보 (제목, 저자, 출판사)",
    "줄거리 요약",
    "인상 깊은 구절/내용",
    "느낀 점 및 생각",
    "비판적 분석 (선택)",
    "추천 대상",
  ],
}

export const QUESTION_TYPES: { value: string; label: string }[] = [
  { value: "concept", label: "개념 설명" },
  { value: "problem_solving", label: "문제 해결" },
  { value: "code_review", label: "코드 리뷰" },
  { value: "learning_method", label: "학습 방법" },
  { value: "other", label: "기타" },
]
